### ISSUE TITLE
can we use this package to manipulate user details available in active directory database?

### ISSUE THREAD

**Issue by virajbahulkar** [jsumners/adldap#4]

**Comment by jsumners** [comment]
Have you investigated the `replace`, `replaceAttribute`, and `incrementAttribute` methods?

**Comment by virajbahulkar** [comment]
yes i had tried ,but not able to make it.

**Comment by jsumners** [comment]
I’m sorry, you’re not being very helpful. What have you tried? Are you seeing an error message? I cannot even attempt to help you if you don’t provide any information.
