### ISSUE TITLE
What info can I access from my AD server?

### ISSUE THREAD

**Issue by christian-hess-94** [jsumners/adldap#5]
I wish to access some other types of info like phone number, description, etc.
Is it possible to access this info with this library? I have tried several other already and none enable me to access these types of more specific information.

**Comment by jsumners** [comment]
Whatever information can be returned by LDAP queries.

https://github.com/jsumners/adldap/blob/6dcd35ad560dae7a5f0b8e9486890d42a628042c/api.md#adldapclientsearchbase-options-controls--promise
